name: "Releaser Linter"
description: "Checks PR titles for semantic correctness"

inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Semantic PR Title Lint
      uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
